### ISSUE TITLE
Marko 5 - are there vision docs ?

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/x#1]
Hey, just curious if you have any docs on your vision for marko 5 ?

Is there an existing place for discussion of features / ideas ?

I just not saw you had created @marko-tags/match-media repo which I think is quite intersting too.. Have you thought of the idea of being able to use namespaced tags - something like 

```
<@marko-tags/match-media({ mobile, tablet, desktop })
  mobile="(max-width: 767px)"
  tablet="(min-width: 768px) and (max-width: 1024px)"
  desktop="(min-width: 1025px)"
>
...
</>
```

And have the compiler hook into npm or yarn and pull in the deps

**Comment by DylanPiercey** [comment]
@cameronbraid this is a good idea. We've got a bunch of ideas floating around at the moment but haven't fully formalized things publicly. Most likely Marko 5 is a ways out depending on the core teams bandwidth.

I'll sync up with @mlrawlings tomorrow and see if we can put some of our ideas out there and get some more community feedback. Perhaps in our [experiment repo](https://github.com/marko-js/x).
